-- CREATE DATABASE

CREATE DATABASE [commerce]
 CONTAINMENT = NONE
GO

ALTER DATABASE [commerce] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [commerce] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [commerce] SET ANSI_NULLS OFF
GO
ALTER DATABASE [commerce] SET ANSI_PADDING OFF
GO
ALTER DATABASE [commerce] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [commerce] SET ARITHABORT OFF
GO
ALTER DATABASE [commerce] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [commerce] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [commerce] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [commerce] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [commerce] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [commerce] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [commerce] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [commerce] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [commerce] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [commerce] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [commerce] SET  DISABLE_BROKER
GO
ALTER DATABASE [commerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [commerce] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [commerce] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [commerce] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [commerce] SET  READ_WRITE
GO
ALTER DATABASE [commerce] SET RECOVERY FULL
GO
ALTER DATABASE [commerce] SET  MULTI_USER
GO
ALTER DATABASE [commerce] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [commerce] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [commerce] SET DELAYED_DURABILITY = DISABLED
GO

USE [commerce]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO

USE [commerce]
GO

IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [commerce] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

-- CREATE TABLES

CREATE TABLE [dbo].[product](
	[id] [int] NOT NULL,
	[name] [varchar](255) NOT NULL,
	[status] [char](1) NULL,
 CONSTRAINT [PK_product] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

-- USERS TO ACCESS DATABASE WITH PASSWORD AUTHENTICATION

exec sp_configure 'contained database authentication', 1
GO

reconfigure
GO

alter database commerce set containment = partial
GO

CREATE USER admin01 WITH PASSWORD='sqlserver', DEFAULT_LANGUAGE=[Brazilian], DEFAULT_SCHEMA=[<database_name>];
GO